#!/usr/bin/env sh

set -e

echo "\n=========="
echo "Setting up Vim\n"

echo "Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim || echo "Vundle already installed"

echo "Installing vim plugins"
vim +PlugInstall +qa

echo "Creating undo directory"
mkdir -p ~/.vim/undo || echo "Undo directory exists"
