add_newline = false

format = "$directory$git_branch$git_status$cmd_duration$character"

[directory]
style = "bold blue"
truncate_to_repo = true

[git_branch]
symbol = "⎇ "
style = "bold purple"

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style)"

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
style = "bold yellow"
